from enum import Enum


class JobStage(Enum):
    UPLOAD = "UPLOAD"
    VALIDATION = "VALIDATION"
    EXTRACTION = "EXTRACTION"
    CHUNKING = "CHUNKING"
    EMBEDDING = "EMBEDDING"
    VECTOR_INDEX = "VECTOR_INDEX"
    FINALIZATION = "FINALIZATION"