from enum import Enum


class ModelRole(str, Enum):
    QUERY_ANALYZER = "QUERY_ANALYZER"
    RETRIEVAL_PLANNER = "RETRIEVAL_PLANNER"
    ANSWER_GENERATOR = "ANSWER_GENERATOR"
    CITATION_VALIDATOR = "CITATION_VALIDATOR"